# http://localhost:9090/
global:
  scrape_interval: 15s # By default, scrape targets every 5 seconds.
  evaluation_interval: 15s
  # body_size_limit: 5MB
  # sample_limit: 1500
  # target_limit: 30
  # label_limit: 30
  # label_name_length_limit: 200
  # label_value_length_limit: 200
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'account-ingestor'
    # environment: Production
    # service: Prometheus
    # region: EU
    # dc: eu-west-1

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules.yml'

scrape_configs:
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  # Container platform metrics
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  # OS platform metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Server App metrics
  - job_name: 'account-ingestor-metrics'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['ingestor:3000']
