version: '3.8'

services:
  postgres:
    container_name: defi_toolbox_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defi_toolbox
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: